language: python
python:
    - "3.6"
install:
    - pip install codecov
    - pip install pytest-cov
    - pip install .
# command to run tests
script:
    - py.test --cov=./

after_success:
    - codecov
